FROM openjdk:8
env name=Rushabh
label email="Rushahbpawar@gmai.com"
run echo "welcome to new world of java programming"
add /target/docker-java-jenkins-project.jar docker-java-jenkins-project.jar
cmd [ "java", "jar", "docker-java-jenkins-project.jar" ]